--> Data: collection of information
--> DBMS: A software required to maintain database
--> DBMS: two types RDBMS, nosql
--> RDBMS: If there is a relation between tables through keys i.e., RDDMS - realtional database management system
--> nosql: collection of data in different formats json,graphs etc.,
--> sql: structured query language
--> Query: a question or a requirement
--> Database : group of tables,views,functions
--> schema: logical seperation of a database. If schema is not mentioned by default the default one dbo - database owner
--> table:collection of data inside a table in rows and records.Since these tables having relation betwenn them we call these as a relational database management system.
--> row: a record of a data
--> column: an attribute/field of a table eg: age,marks

-->> RDBMS : MS SQL, MySQL, PostgreSQl
-------------------------------------------------------
	--> Relationships:
		-- One to one(1:1)
		-- One to many(1:n)
		-- Many to Many(n:m)
	-->Keys:(Keys that helps)
		-- Candidate:      Any column that could serve as a primary key
		-- Surrogate key:  A unique and not null key but generated by system
		-- Natural Keys:   Any unique and not null data from real world
		-- Primary key:    uniqueness + not null (one among a candidate key)
		-- Foriegn key:    references a primary key in another table to establish relationships
		-- Composite key:  multiple primary keys
		

-->> SQL Commands
	--> DDL: Data Definition Language - Database level
			-- CREATE, ALTER, DROP, TRUNCATE, RENAME
	--> DML: Data Manipulation Language - Table Level
			-- SELECT, INSERT, UPDATE, DELETE, MERGE
	--> DCL: Data Control Language - Control and access permissions
			-- GRANT, REVOKE, DENY
	--> TCL: Transaction Control Language - Manage Transactions
			-- COMMIT, ROLLBACK, SAVEPOINT



-->> DDL -  Data Definition Language
------------------------------------------------------------------------
	--> To create or make changes schema level.
		-- CREATE, ALTER, DROP, TRUNCATE, RENAME

	-- 1. Create Database
		CREATE DATABASE College;
		go

	-- 2. List All Databases in a system
		SELECT name 
		FROM SYS.DATABASES;
	
	-- 3. To see only databases created by User
		SELECT name
		FROM SYS.DATABASES 
		WHERE database_id > 4;

	-- 4. With file specification (SQL Server)
		CREATE DATABASE Company
		ON PRIMARY (
			NAME = 'SalesDB_Data', --name for database to understand
			FILENAME = 'D:\SQL2025\SalesDB.mdf', -- In background SQL stores this file in this format
			SIZE = 100MB, -- Initial size of a db
			MAXSIZE = 1GB, -- Max limit of a db it can reach to 1 GB 
			FILEGROWTH = 10MB -- E
		)
		LOG ON (
			NAME = 'SalesDB Log', -- name of a log for db
			FILENAME = 'D:\SQL2025\SalesDB_log.ldf', -- File name and location of log file
			SIZE = 50MB -- size of a log file
		);
		go

	-- 5. Switch to a database
		USE Company;
		GO

	--> Data Types
		--  TINYINT, INT, BIGINT, FLOAT, DECIMAL(p,s),CHAR(n), VARCHAR(n),NVARCHAR(n),DATE,DATEIME2,BIT(0 or 1),UNIQUEIDENTIFIER

	-->Schema
		-- create a schema
		CREATE SCHEMA hr AUTHORIZATION dbo;
		GO

		-- to see all schemas created by user
		SELECT name FROM sys.schemas WHERE name NOT LIKE 'db_%' and name  NOT IN ('dbo','guest','sys','INFORMATION_SCHEMA');

		--create a tale with in schema
		CREATE TABLE hr.Employees(
			EmployeeId INT NOT NULL PRIMARY KEY,
			FirstName VARCHAR(50) NOT NULL
		);

		-- If schema is not mentioned then by default it will stored as 'dbo' schema
		CREATE TABLE Students(
			StudentId INT NOT NULL PRIMARY KEY,
			FirstName Varchar(50) NOT Null,
			LastName Varchar(50) Not Null,
			Email Varchar(50) Not Null UNIQUE
		)

		--Accessing a schema-qualified table
		SELECT * FROM hr.Employees;

		-- To see all details of a table
			-- By using Stored procedure
			EXEC sp_help 'academics.Students';

			-- By using a view
			SELECT 
				* 
			FROM 
				INFORMATION_SCHEMA.COLUMNS
			WHERE
				TABLE_SCHEMA  = 'academics' AND TABLE_NAME = 'Students';
	
	--> Alter 
		
	-->Add Column
		--Add a single column 
		ALTER TABLE hr.Employees
		ADD IsActive BIT NOT NULL;

		--Add multiple columns
		ALTER TABLE hr.Employees
		ADD MiddleName Varchar(50),
		    LastName Varchar(50);

		--Add Column with Constraint
		ALTER TABLE hr.Employees
		ADD ManagerId INT REFERENCES Employees(EmployeeID);

	-->Modify Column
		--Change datatype or size
		ALTER TABLE hr.Employees
		ALTER COLUMN LastName VARCHAR(100) Not NUll;

		--Add a default contraint
		ALTER TABLE hr.Employees
		ADD CONSTRAINT DF_IsActive DEFAULT 1 FOR IsActive;

	--> Drop Column
		--Drop a column(No Constraint)
		ALTER TABLE hr.Employees
		DROP COLUMN MiddleName;

		--Drop Constraint first then drop a column(If constraint attached)
		ALTER TABLE hr.Employees DROP CONSTRAINT DF_IfActive;
		ALTER TABLE Hr.Employees DROP COLUMN IsActive;

		/*
		 Common Mistake:
		You cannot drop a column that has a constraint on it. Always identify and drop the constraint 
		first using: 
		SELECT * FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('hr.Employees')		
		*/
		

		--Drop Database
		DROP DATABASE Company;

		--Drop Schema
		DROP SCHEMA hr;

		-- Drop Table
		DROP TABLE hr.Employees;

		--Safe Drop
		DROP TABLE IF EXISTS hr.Employees;

	--> Truncate Table : To delete only data in a table not entire table		
		--Truncate a table
			--Cannot truncate a table referenced by FK
			--Must disable or drop a constraint first then truncate a table
			TRUNCATE TABLE hr.Employees;

	-->RENAME
		--Rename a table
		EXEC sp_rename 'hr.Employees','hr.Employee' ;

		--Rename a Stored Procedure or View
		EXEC sp_rename 'sp_oldname','sp_newname';
		EXEC sp_rename 'vw_oldname', 'vd_newname';

		--Rename a column
		EXEC sp_rename 'OldColumn','NewColumn','COLUMN';

		--Rename an Index
		EXEC sp_rename 'ix_oldname','ix_newname', 'INDEX';

		--Rename a constraint('C', 'F', 'PK')
		EXEC sp_rename 'DF_is_Active', 'DF_staff_status_flag', 'OBJECT';


-->> Constraints
	--PRIMARY KEY, FOREIGN KEY, UNIQUE, NOT NULL, CHECK, DEFAULT
	--> Primary Key
		-- Unique values and not null

		--Inline Defination
		CREATE TABLE Employees(
			EmployeeID INT NOT NULL PRIMARY KEY,
			FirstName VARCHAR(50) NOT NULL,
			LASTNAME VARCHAR(50) NOT NULL
		);
		

		--Table-level constraint
		CREATE TABLE Employees1(
			EmployeeId INT NOT NULL,
			FirstName VARCHAR(50) NOT NULL,
			LastName VARCHAR(50) NOT NUll,
			CONSTRAINT PK_Employees PRIMARY KEY(EmployeeId)
		)

		--Composite Primary Key
		CREATE TABLE OrderDetails(
			OrderId INT NOT NULL,
			ProductId INT NOT NULL,
			Quantity INT NOT NULL,
			CONSTRAINT PK_OrderDetails PRIMARY KEY(OrderId,ProductId)
		)


	-->Foreign Key
		--A FK in one table is a PK of another table. We cannot reference FK value with a PK value exists.

		--Table with PK
		CREATE TABLE Departments(
			DeptId INT NOT NULL PRIMARY KEY,
			DeptName VARCHAR(50) NOT NULL
		)

		CREATE TABLE Employees2(
			EmployeeID INT NOT NULL PRIMARY KEY,
			FirstName VARCHAR(50) NOT NULL,
			DeptID INT,
			CONSTRAINT FK_Emp_Dept FOREIGN KEY (DeptID)
			REFERENCES Departments(DeptId)
			ON DELETE SET NULL
			ON UPDATE CASCADE		
		);

	-->Unique,NOT NULL, CHECK, DEFAULT
		CREATE TABLE Employees3(
			EmployeeID INT NOT NULL,
			FirstName VARCHAR(50) NOT NULL,
			LastName VARCHAR(50) NOT NULL,
			Email VARCHAR(30) NOT NULL,
			Age INT NOT NULL,
			IsActive BIT,
			CONSTRAINT PK_Employees PRIMARY KEY(EmployeeID),
			CONSTRAINT UQ_Employees UNIQUE (Email),
			CONSTRAINT DF_Is_Active DEFAULT 1 FOR Is_Active
		)

		
		










	



	


		











